version: '3.8'

services:
  todo-frontend:
    extends:
      file: ./todo-frontend/compose.dev.yml
      service: todo-frontend
  nginx-proxy:
    image: nginx:1.23.4-alpine
    volumes:
      - ./nginx.dev.config:/etc/nginx/nginx.dev.conf:ro
    ports:
      - 8080:80
    container_name: fso_nginx
    depends_on:
      - todo-frontend