version: "3.8"

services:
  react-app:
    image: fso/bloglist-frontend-dev
    build:
      context: ./client
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./client:/usr/src/app
    container_name: fso_bloglist_frontend_dev
    ports:
      - "3000:3000"
  express-server:
    image: fso/bloglist-server-dev
    build:
      context: ./server
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./server:/usr/src/app
    container_name: fso_bloglist_backend_dev
    ports:
      - "3003:3003"