version: '3.8'

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=todo_backend_db
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redisdb:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data
  todo-backend-dev:
    image: fso12/todo-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3003:3003
    container_name: todo_backend_dev
    volumes:
      - ./:/usr/src/app
    env_file: .env
  debugger-busybox:
    image: busybox

volumes:
  mongo_data:
  redis_data: